//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 5/31/2013 4:09:04 PM
namespace Magelia.WebStore.Client
{
    public class EnhancedCatalogServiceClient : Magelia.WebStore.Client.EnhancedCatalogServiceClientBase, ICatalogServiceClient
    {
        private global::Magelia.WebStore.ServiceQueryable<Attribute> _attributes;
        private global::Magelia.WebStore.ServiceQueryable<AttributeValue> _attributeValues;
        private global::Magelia.WebStore.ServiceQueryable<BaseProduct> _products;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedCatalog> _catalogs;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedCategory> _categories;
        private global::Magelia.WebStore.ServiceQueryable<File> _files;
        private global::Magelia.WebStore.ServiceQueryable<FileTag> _fileTags;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedBrand> _brands;
        private global::Magelia.WebStore.ServiceQueryable<CategoryHierarchy> _categoryHierarchies;
        private global::Magelia.WebStore.ServiceQueryable<CategoryProduct> _categoryProducts;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedSupplier> _suppliers;
        private global::Magelia.WebStore.ServiceQueryable<ProductLink> _productLinks;
        private global::Magelia.WebStore.ServiceQueryable<Price> _prices;
        private global::Magelia.WebStore.ServiceQueryable<TaxDetail> _taxDetails;
        private global::Magelia.WebStore.ServiceQueryable<DiscountDetail> _discountDetails;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedDiscount> _discounts;
        private global::Magelia.WebStore.ServiceQueryable<BundleItem> _bundleItems;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedCarrier> _carriers;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedContinent> _continents;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedCountry> _countries;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedCurrency> _currencies;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedRegion> _regions;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedOrderChannel> _orderChannels;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedSegment> _segments;
        private global::Magelia.WebStore.ServiceQueryable<ExtendedWarehouse> _warehouses;
        public EnhancedCatalogServiceClient(System.Lazy<IStoreServiceClient> storeService, ICatalogContext catalogContext) :
            base(storeService, catalogContext)
        {
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<Attribute> Attributes
        {
            get
            {
                if ((this._attributes == null))
                {
                    this._attributes = base.CreateQuery<Attribute>("Attributes");
                }
                return this._attributes;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<AttributeValue> AttributeValues
        {
            get
            {
                if ((this._attributeValues == null))
                {
                    this._attributeValues = base.CreateQuery<AttributeValue>("AttributeValues");
                }
                return this._attributeValues;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<BaseProduct> Products
        {
            get
            {
                if ((this._products == null))
                {
                    this._products = base.CreateQuery<BaseProduct>("Products");
                }
                return this._products;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedCatalog> Catalogs
        {
            get
            {
                if ((this._catalogs == null))
                {
                    this._catalogs = base.CreateQuery<ExtendedCatalog>("Catalogs");
                }
                return this._catalogs;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedCategory> Categories
        {
            get
            {
                if ((this._categories == null))
                {
                    this._categories = base.CreateQuery<ExtendedCategory>("Categories");
                }
                return this._categories;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<File> Files
        {
            get
            {
                if ((this._files == null))
                {
                    this._files = base.CreateQuery<File>("Files");
                }
                return this._files;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<FileTag> FileTags
        {
            get
            {
                if ((this._fileTags == null))
                {
                    this._fileTags = base.CreateQuery<FileTag>("FileTags");
                }
                return this._fileTags;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedBrand> Brands
        {
            get
            {
                if ((this._brands == null))
                {
                    this._brands = base.CreateQuery<ExtendedBrand>("Brands");
                }
                return this._brands;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<CategoryHierarchy> CategoryHierarchies
        {
            get
            {
                if ((this._categoryHierarchies == null))
                {
                    this._categoryHierarchies = base.CreateQuery<CategoryHierarchy>("CategoryHierarchies");
                }
                return this._categoryHierarchies;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<CategoryProduct> CategoryProducts
        {
            get
            {
                if ((this._categoryProducts == null))
                {
                    this._categoryProducts = base.CreateQuery<CategoryProduct>("CategoryProducts");
                }
                return this._categoryProducts;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedSupplier> Suppliers
        {
            get
            {
                if ((this._suppliers == null))
                {
                    this._suppliers = base.CreateQuery<ExtendedSupplier>("Suppliers");
                }
                return this._suppliers;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ProductLink> ProductLinks
        {
            get
            {
                if ((this._productLinks == null))
                {
                    this._productLinks = base.CreateQuery<ProductLink>("ProductLinks");
                }
                return this._productLinks;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<Price> Prices
        {
            get
            {
                if ((this._prices == null))
                {
                    this._prices = base.CreateQuery<Price>("Prices");
                }
                return this._prices;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<TaxDetail> TaxDetails
        {
            get
            {
                if ((this._taxDetails == null))
                {
                    this._taxDetails = base.CreateQuery<TaxDetail>("TaxDetails");
                }
                return this._taxDetails;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<DiscountDetail> DiscountDetails
        {
            get
            {
                if ((this._discountDetails == null))
                {
                    this._discountDetails = base.CreateQuery<DiscountDetail>("DiscountDetails");
                }
                return this._discountDetails;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedDiscount> Discounts
        {
            get
            {
                if ((this._discounts == null))
                {
                    this._discounts = base.CreateQuery<ExtendedDiscount>("Discounts");
                }
                return this._discounts;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<BundleItem> BundleItems
        {
            get
            {
                if ((this._bundleItems == null))
                {
                    this._bundleItems = base.CreateQuery<BundleItem>("BundleItems");
                }
                return this._bundleItems;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedCarrier> Carriers
        {
            get
            {
                if ((this._carriers == null))
                {
                    this._carriers = base.CreateQuery<ExtendedCarrier>("Carriers");
                }
                return this._carriers;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedContinent> Continents
        {
            get
            {
                if ((this._continents == null))
                {
                    this._continents = base.CreateQuery<ExtendedContinent>("Continents");
                }
                return this._continents;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedCountry> Countries
        {
            get
            {
                if ((this._countries == null))
                {
                    this._countries = base.CreateQuery<ExtendedCountry>("Countries");
                }
                return this._countries;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedCurrency> Currencies
        {
            get
            {
                if ((this._currencies == null))
                {
                    this._currencies = base.CreateQuery<ExtendedCurrency>("Currencies");
                }
                return this._currencies;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedRegion> Regions
        {
            get
            {
                if ((this._regions == null))
                {
                    this._regions = base.CreateQuery<ExtendedRegion>("Regions");
                }
                return this._regions;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedOrderChannel> OrderChannels
        {
            get
            {
                if ((this._orderChannels == null))
                {
                    this._orderChannels = base.CreateQuery<ExtendedOrderChannel>("OrderChannels");
                }
                return this._orderChannels;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedSegment> Segments
        {
            get
            {
                if ((this._segments == null))
                {
                    this._segments = base.CreateQuery<ExtendedSegment>("Segments");
                }
                return this._segments;
            }
        }
        public virtual global::Magelia.WebStore.ServiceQueryable<ExtendedWarehouse> Warehouses
        {
            get
            {
                if ((this._warehouses == null))
                {
                    this._warehouses = base.CreateQuery<ExtendedWarehouse>("Warehouses");
                }
                return this._warehouses;
            }
        }
    }
    public interface ICatalogServiceClient : global::Magelia.WebStore.Client.ICatalogServiceClientBase
    {
        global::Magelia.WebStore.ServiceQueryable<Attribute> Attributes
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<AttributeValue> AttributeValues
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<BaseProduct> Products
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedCatalog> Catalogs
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedCategory> Categories
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<File> Files
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<FileTag> FileTags
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedBrand> Brands
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<CategoryHierarchy> CategoryHierarchies
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<CategoryProduct> CategoryProducts
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedSupplier> Suppliers
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ProductLink> ProductLinks
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<Price> Prices
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<TaxDetail> TaxDetails
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<DiscountDetail> DiscountDetails
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedDiscount> Discounts
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<BundleItem> BundleItems
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedCarrier> Carriers
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedContinent> Continents
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedCountry> Countries
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedCurrency> Currencies
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedRegion> Regions
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedOrderChannel> OrderChannels
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedSegment> Segments
        {
            get;
        }
        global::Magelia.WebStore.ServiceQueryable<ExtendedWarehouse> Warehouses
        {
            get;
        }
    }
    public class Attribute
    {
        private System.Guid _attributeId;
        private string _attributeTypeCode;
        private string _productTypeCode;
        private string _code;
        private string _name;
        private int _order;
        private string _description;
        private bool _showInProductList;
        private bool _showInProductDetail;
        private bool _allowFilter;
        private bool _allowSelection;
        private System.Collections.Generic.IEnumerable<AttributeValue> _attributeValues;
        public virtual System.Guid AttributeId
        {
            get
            {
                return this._attributeId;
            }
            set
            {
                this._attributeId = value;
            }
        }
        public virtual string AttributeTypeCode
        {
            get
            {
                return this._attributeTypeCode;
            }
            set
            {
                this._attributeTypeCode = value;
            }
        }
        public virtual string ProductTypeCode
        {
            get
            {
                return this._productTypeCode;
            }
            set
            {
                this._productTypeCode = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual int Order
        {
            get
            {
                return this._order;
            }
            set
            {
                this._order = value;
            }
        }
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        public virtual bool ShowInProductList
        {
            get
            {
                return this._showInProductList;
            }
            set
            {
                this._showInProductList = value;
            }
        }
        public virtual bool ShowInProductDetail
        {
            get
            {
                return this._showInProductDetail;
            }
            set
            {
                this._showInProductDetail = value;
            }
        }
        public virtual bool AllowFilter
        {
            get
            {
                return this._allowFilter;
            }
            set
            {
                this._allowFilter = value;
            }
        }
        public virtual bool AllowSelection
        {
            get
            {
                return this._allowSelection;
            }
            set
            {
                this._allowSelection = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<AttributeValue> AttributeValues
        {
            get
            {
                return this._attributeValues;
            }
            set
            {
                this._attributeValues = value;
            }
        }
    }
    public class AttributeValue
    {
        private System.Guid _attributeValueId;
        private System.Guid _productId;
        private System.Guid _attributeId;
        private string _stringValue;
        private string _listCode;
        private string _listValue;
        private System.Nullable<bool> _booleanValue;
        private System.Nullable<int> _intValue;
        private System.Nullable<decimal> _decimalValue;
        private System.Nullable<System.DateTimeOffset> _dateTimeValue;
        private BaseProduct _product;
        private Attribute _attribute;
        private System.Collections.Generic.IEnumerable<File> _files;
        public virtual System.Guid AttributeValueId
        {
            get
            {
                return this._attributeValueId;
            }
            set
            {
                this._attributeValueId = value;
            }
        }
        public virtual System.Guid ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }
        public virtual System.Guid AttributeId
        {
            get
            {
                return this._attributeId;
            }
            set
            {
                this._attributeId = value;
            }
        }
        public virtual string StringValue
        {
            get
            {
                return this._stringValue;
            }
            set
            {
                this._stringValue = value;
            }
        }
        public virtual string ListCode
        {
            get
            {
                return this._listCode;
            }
            set
            {
                this._listCode = value;
            }
        }
        public virtual string ListValue
        {
            get
            {
                return this._listValue;
            }
            set
            {
                this._listValue = value;
            }
        }
        public virtual System.Nullable<bool> BooleanValue
        {
            get
            {
                return this._booleanValue;
            }
            set
            {
                this._booleanValue = value;
            }
        }
        public virtual System.Nullable<int> IntValue
        {
            get
            {
                return this._intValue;
            }
            set
            {
                this._intValue = value;
            }
        }
        public virtual System.Nullable<decimal> DecimalValue
        {
            get
            {
                return this._decimalValue;
            }
            set
            {
                this._decimalValue = value;
            }
        }
        public virtual System.Nullable<System.DateTimeOffset> DateTimeValue
        {
            get
            {
                return this._dateTimeValue;
            }
            set
            {
                this._dateTimeValue = value;
            }
        }
        public virtual BaseProduct Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }
        }
        public virtual Attribute Attribute
        {
            get
            {
                return this._attribute;
            }
            set
            {
                this._attribute = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<File> Files
        {
            get
            {
                return this._files;
            }
            set
            {
                this._files = value;
            }
        }
    }
    public class BaseProduct
    {
        private System.Guid _productId;
        private System.Guid _catalogId;
        private string _productTypeCode;
        private string _typeName;
        private System.Nullable<System.Guid> _supplierId;
        private System.Nullable<System.Guid> _brandId;
        private System.Nullable<decimal> _weight;
        private System.Nullable<decimal> _height;
        private System.Nullable<decimal> _width;
        private System.Nullable<decimal> _length;
        private bool _isOnline;
        private string _name;
        private string _shortDescription;
        private string _longDescription;
        private string _additionalDescription;
        private Catalog _catalog;
        private Supplier _supplier;
        private Brand _brand;
        private System.Collections.Generic.IEnumerable<CategoryProduct> _productCategories;
        private System.Collections.Generic.IEnumerable<ProductLink> _productLinks;
        private System.Collections.Generic.IEnumerable<ProductLink> _productLinkings;
        private System.Collections.Generic.IEnumerable<AttributeValue> _attributeValues;
        public virtual System.Guid ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }
        public virtual System.Guid CatalogId
        {
            get
            {
                return this._catalogId;
            }
            set
            {
                this._catalogId = value;
            }
        }
        public virtual string ProductTypeCode
        {
            get
            {
                return this._productTypeCode;
            }
            set
            {
                this._productTypeCode = value;
            }
        }
        public virtual string TypeName
        {
            get
            {
                return this._typeName;
            }
            set
            {
                this._typeName = value;
            }
        }
        public virtual System.Nullable<System.Guid> SupplierId
        {
            get
            {
                return this._supplierId;
            }
            set
            {
                this._supplierId = value;
            }
        }
        public virtual System.Nullable<System.Guid> BrandId
        {
            get
            {
                return this._brandId;
            }
            set
            {
                this._brandId = value;
            }
        }
        public virtual System.Nullable<decimal> Weight
        {
            get
            {
                return this._weight;
            }
            set
            {
                this._weight = value;
            }
        }
        public virtual System.Nullable<decimal> Height
        {
            get
            {
                return this._height;
            }
            set
            {
                this._height = value;
            }
        }
        public virtual System.Nullable<decimal> Width
        {
            get
            {
                return this._width;
            }
            set
            {
                this._width = value;
            }
        }
        public virtual System.Nullable<decimal> Length
        {
            get
            {
                return this._length;
            }
            set
            {
                this._length = value;
            }
        }
        public virtual bool IsOnline
        {
            get
            {
                return this._isOnline;
            }
            set
            {
                this._isOnline = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual string ShortDescription
        {
            get
            {
                return this._shortDescription;
            }
            set
            {
                this._shortDescription = value;
            }
        }
        public virtual string LongDescription
        {
            get
            {
                return this._longDescription;
            }
            set
            {
                this._longDescription = value;
            }
        }
        public virtual string AdditionalDescription
        {
            get
            {
                return this._additionalDescription;
            }
            set
            {
                this._additionalDescription = value;
            }
        }
        public virtual Catalog Catalog
        {
            get
            {
                return this._catalog;
            }
            set
            {
                this._catalog = value;
            }
        }
        public virtual Supplier Supplier
        {
            get
            {
                return this._supplier;
            }
            set
            {
                this._supplier = value;
            }
        }
        public virtual Brand Brand
        {
            get
            {
                return this._brand;
            }
            set
            {
                this._brand = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<CategoryProduct> ProductCategories
        {
            get
            {
                return this._productCategories;
            }
            set
            {
                this._productCategories = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<ProductLink> ProductLinks
        {
            get
            {
                return this._productLinks;
            }
            set
            {
                this._productLinks = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<ProductLink> ProductLinkings
        {
            get
            {
                return this._productLinkings;
            }
            set
            {
                this._productLinkings = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<AttributeValue> AttributeValues
        {
            get
            {
                return this._attributeValues;
            }
            set
            {
                this._attributeValues = value;
            }
        }
    }
    public class ReferenceProduct : BaseProduct
    {
        private string _sKU;
        private System.Nullable<System.DateTimeOffset> _startDate;
        private System.Nullable<System.DateTimeOffset> _endDate;
        private System.Nullable<System.Guid> _priceIdWithLowerQuantity;
        private Price _priceWithLowerQuantity;
        private System.Collections.Generic.IEnumerable<Price> _prices;
        private System.Collections.Generic.IEnumerable<BundleItem> _bundlingItems;
        public virtual string SKU
        {
            get
            {
                return this._sKU;
            }
            set
            {
                this._sKU = value;
            }
        }
        public virtual System.Nullable<System.DateTimeOffset> StartDate
        {
            get
            {
                return this._startDate;
            }
            set
            {
                this._startDate = value;
            }
        }
        public virtual System.Nullable<System.DateTimeOffset> EndDate
        {
            get
            {
                return this._endDate;
            }
            set
            {
                this._endDate = value;
            }
        }
        public virtual System.Nullable<System.Guid> PriceIdWithLowerQuantity
        {
            get
            {
                return this._priceIdWithLowerQuantity;
            }
            set
            {
                this._priceIdWithLowerQuantity = value;
            }
        }
        public virtual Price PriceWithLowerQuantity
        {
            get
            {
                return this._priceWithLowerQuantity;
            }
            set
            {
                this._priceWithLowerQuantity = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<Price> Prices
        {
            get
            {
                return this._prices;
            }
            set
            {
                this._prices = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<BundleItem> BundlingItems
        {
            get
            {
                return this._bundlingItems;
            }
            set
            {
                this._bundlingItems = value;
            }
        }
    }
    public class BundleProduct : ReferenceProduct
    {
        private System.Collections.Generic.IEnumerable<BundleItem> _bundleItems;
        public virtual System.Collections.Generic.IEnumerable<BundleItem> BundleItems
        {
            get
            {
                return this._bundleItems;
            }
            set
            {
                this._bundleItems = value;
            }
        }
    }
    public class ExtendedBundleProduct : BundleProduct
    {
    }
    public class StandardProduct : ReferenceProduct
    {
    }
    public class ExtendedStandardProduct : StandardProduct
    {
    }
    public class VariantProduct : ReferenceProduct
    {
        private System.Guid _variableProductId;
        private bool _isDefault;
        private int _order;
        private VariableProduct _variableProduct;
        public virtual System.Guid VariableProductId
        {
            get
            {
                return this._variableProductId;
            }
            set
            {
                this._variableProductId = value;
            }
        }
        public virtual bool IsDefault
        {
            get
            {
                return this._isDefault;
            }
            set
            {
                this._isDefault = value;
            }
        }
        public virtual int Order
        {
            get
            {
                return this._order;
            }
            set
            {
                this._order = value;
            }
        }
        public virtual VariableProduct VariableProduct
        {
            get
            {
                return this._variableProduct;
            }
            set
            {
                this._variableProduct = value;
            }
        }
    }
    public class ExtendedVariantProduct : VariantProduct
    {
    }
    public class VariableProduct : BaseProduct
    {
        private System.Nullable<System.Guid> _defaultVariantProductId;
        private string _code;
        private VariantProduct _defaultVariantProduct;
        private System.Collections.Generic.IEnumerable<VariantProduct> _variantProducts;
        public virtual System.Nullable<System.Guid> DefaultVariantProductId
        {
            get
            {
                return this._defaultVariantProductId;
            }
            set
            {
                this._defaultVariantProductId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual VariantProduct DefaultVariantProduct
        {
            get
            {
                return this._defaultVariantProduct;
            }
            set
            {
                this._defaultVariantProduct = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<VariantProduct> VariantProducts
        {
            get
            {
                return this._variantProducts;
            }
            set
            {
                this._variantProducts = value;
            }
        }
    }
    public class ExtendedVariableProduct : VariableProduct
    {
    }
    public class Catalog
    {
        private System.Guid _catalogId;
        private string _code;
        private System.Nullable<System.DateTimeOffset> _startDate;
        private System.Nullable<System.DateTimeOffset> _endDate;
        private string _name;
        private string _shortDescription;
        private string _longDescription;
        private System.Collections.Generic.IEnumerable<Category> _categories;
        private System.Collections.Generic.IEnumerable<BaseProduct> _products;
        private System.Collections.Generic.IEnumerable<File> _files;
        public virtual System.Guid CatalogId
        {
            get
            {
                return this._catalogId;
            }
            set
            {
                this._catalogId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual System.Nullable<System.DateTimeOffset> StartDate
        {
            get
            {
                return this._startDate;
            }
            set
            {
                this._startDate = value;
            }
        }
        public virtual System.Nullable<System.DateTimeOffset> EndDate
        {
            get
            {
                return this._endDate;
            }
            set
            {
                this._endDate = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual string ShortDescription
        {
            get
            {
                return this._shortDescription;
            }
            set
            {
                this._shortDescription = value;
            }
        }
        public virtual string LongDescription
        {
            get
            {
                return this._longDescription;
            }
            set
            {
                this._longDescription = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<Category> Categories
        {
            get
            {
                return this._categories;
            }
            set
            {
                this._categories = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<BaseProduct> Products
        {
            get
            {
                return this._products;
            }
            set
            {
                this._products = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<File> Files
        {
            get
            {
                return this._files;
            }
            set
            {
                this._files = value;
            }
        }
    }
    public class ExtendedCatalog : Catalog
    {
    }
    public class Category
    {
        private System.Guid _categoryId;
        private System.Guid _catalogId;
        private string _code;
        private bool _isOnline;
        private string _name;
        private string _shortDescription;
        private string _longDescription;
        private Catalog _catalog;
        private System.Collections.Generic.IEnumerable<File> _files;
        private System.Collections.Generic.IEnumerable<CategoryHierarchy> _parentCategoryHierarchies;
        private System.Collections.Generic.IEnumerable<CategoryHierarchy> _childCategoryHierarchies;
        private System.Collections.Generic.IEnumerable<CategoryProduct> _categoryProducts;
        public virtual System.Guid CategoryId
        {
            get
            {
                return this._categoryId;
            }
            set
            {
                this._categoryId = value;
            }
        }
        public virtual System.Guid CatalogId
        {
            get
            {
                return this._catalogId;
            }
            set
            {
                this._catalogId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual bool IsOnline
        {
            get
            {
                return this._isOnline;
            }
            set
            {
                this._isOnline = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual string ShortDescription
        {
            get
            {
                return this._shortDescription;
            }
            set
            {
                this._shortDescription = value;
            }
        }
        public virtual string LongDescription
        {
            get
            {
                return this._longDescription;
            }
            set
            {
                this._longDescription = value;
            }
        }
        public virtual Catalog Catalog
        {
            get
            {
                return this._catalog;
            }
            set
            {
                this._catalog = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<File> Files
        {
            get
            {
                return this._files;
            }
            set
            {
                this._files = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<CategoryHierarchy> ParentCategoryHierarchies
        {
            get
            {
                return this._parentCategoryHierarchies;
            }
            set
            {
                this._parentCategoryHierarchies = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<CategoryHierarchy> ChildCategoryHierarchies
        {
            get
            {
                return this._childCategoryHierarchies;
            }
            set
            {
                this._childCategoryHierarchies = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<CategoryProduct> CategoryProducts
        {
            get
            {
                return this._categoryProducts;
            }
            set
            {
                this._categoryProducts = value;
            }
        }
    }
    public class ExtendedCategory : Category
    {
    }
    public class File
    {
        private System.Guid _fileId;
        private string _name;
        private string _title;
        private string _alternateText;
        private string _description;
        private string _path;
        private System.DateTimeOffset _creationDate;
        private System.Nullable<System.DateTimeOffset> _lastModificationDate;
        private System.Collections.Generic.IEnumerable<FileTag> _fileTags;
        private System.Collections.Generic.IEnumerable<Catalog> _catalogs;
        private System.Collections.Generic.IEnumerable<Category> _categories;
        private System.Collections.Generic.IEnumerable<AttributeValue> _attributes;
        public virtual System.Guid FileId
        {
            get
            {
                return this._fileId;
            }
            set
            {
                this._fileId = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
            }
        }
        public virtual string AlternateText
        {
            get
            {
                return this._alternateText;
            }
            set
            {
                this._alternateText = value;
            }
        }
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        public virtual string Path
        {
            get
            {
                return this._path;
            }
            set
            {
                this._path = value;
            }
        }
        public virtual System.DateTimeOffset CreationDate
        {
            get
            {
                return this._creationDate;
            }
            set
            {
                this._creationDate = value;
            }
        }
        public virtual System.Nullable<System.DateTimeOffset> LastModificationDate
        {
            get
            {
                return this._lastModificationDate;
            }
            set
            {
                this._lastModificationDate = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<FileTag> FileTags
        {
            get
            {
                return this._fileTags;
            }
            set
            {
                this._fileTags = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<Catalog> Catalogs
        {
            get
            {
                return this._catalogs;
            }
            set
            {
                this._catalogs = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<Category> Categories
        {
            get
            {
                return this._categories;
            }
            set
            {
                this._categories = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<AttributeValue> Attributes
        {
            get
            {
                return this._attributes;
            }
            set
            {
                this._attributes = value;
            }
        }
    }
    public class ApplicationFile : File
    {
    }
    public class AudioFile : File
    {
    }
    public class DocumentFile : File
    {
    }
    public class ImageFile : File
    {
        private System.Collections.Generic.IEnumerable<Brand> _brands;
        public virtual System.Collections.Generic.IEnumerable<Brand> Brands
        {
            get
            {
                return this._brands;
            }
            set
            {
                this._brands = value;
            }
        }
    }
    public class UnknownFile : File
    {
    }
    public class VideoFile : File
    {
    }
    public class FileTag
    {
        private System.Guid _fileTagId;
        private System.Guid _fileId;
        private string _tag;
        private File _file;
        public virtual System.Guid FileTagId
        {
            get
            {
                return this._fileTagId;
            }
            set
            {
                this._fileTagId = value;
            }
        }
        public virtual System.Guid FileId
        {
            get
            {
                return this._fileId;
            }
            set
            {
                this._fileId = value;
            }
        }
        public virtual string Tag
        {
            get
            {
                return this._tag;
            }
            set
            {
                this._tag = value;
            }
        }
        public virtual File File
        {
            get
            {
                return this._file;
            }
            set
            {
                this._file = value;
            }
        }
    }
    public class Brand
    {
        private System.Guid _brandId;
        private string _code;
        private System.Nullable<System.Guid> _logoFileId;
        private System.Collections.Generic.IEnumerable<BaseProduct> _products;
        private ImageFile _logoFile;
        public virtual System.Guid BrandId
        {
            get
            {
                return this._brandId;
            }
            set
            {
                this._brandId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual System.Nullable<System.Guid> LogoFileId
        {
            get
            {
                return this._logoFileId;
            }
            set
            {
                this._logoFileId = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<BaseProduct> Products
        {
            get
            {
                return this._products;
            }
            set
            {
                this._products = value;
            }
        }
        public virtual ImageFile LogoFile
        {
            get
            {
                return this._logoFile;
            }
            set
            {
                this._logoFile = value;
            }
        }
    }
    public class ExtendedBrand : Brand
    {
    }
    public class CategoryHierarchy
    {
        private System.Guid _categoryId;
        private System.Guid _parentCategoryId;
        private int _order;
        private Category _parentCategory;
        private Category _category;
        public virtual System.Guid CategoryId
        {
            get
            {
                return this._categoryId;
            }
            set
            {
                this._categoryId = value;
            }
        }
        public virtual System.Guid ParentCategoryId
        {
            get
            {
                return this._parentCategoryId;
            }
            set
            {
                this._parentCategoryId = value;
            }
        }
        public virtual int Order
        {
            get
            {
                return this._order;
            }
            set
            {
                this._order = value;
            }
        }
        public virtual Category ParentCategory
        {
            get
            {
                return this._parentCategory;
            }
            set
            {
                this._parentCategory = value;
            }
        }
        public virtual Category Category
        {
            get
            {
                return this._category;
            }
            set
            {
                this._category = value;
            }
        }
    }
    public class CategoryProduct
    {
        private System.Guid _categoryId;
        private System.Guid _productId;
        private int _order;
        private Category _category;
        private BaseProduct _product;
        public virtual System.Guid CategoryId
        {
            get
            {
                return this._categoryId;
            }
            set
            {
                this._categoryId = value;
            }
        }
        public virtual System.Guid ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }
        public virtual int Order
        {
            get
            {
                return this._order;
            }
            set
            {
                this._order = value;
            }
        }
        public virtual Category Category
        {
            get
            {
                return this._category;
            }
            set
            {
                this._category = value;
            }
        }
        public virtual BaseProduct Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }
        }
    }
    public class Supplier
    {
        private System.Guid _supplierId;
        private string _code;
        private System.Collections.Generic.IEnumerable<BaseProduct> _products;
        public virtual System.Guid SupplierId
        {
            get
            {
                return this._supplierId;
            }
            set
            {
                this._supplierId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<BaseProduct> Products
        {
            get
            {
                return this._products;
            }
            set
            {
                this._products = value;
            }
        }
    }
    public class ExtendedSupplier : Supplier
    {
    }
    public class ProductLink
    {
        private System.Guid _productLinkId;
        private System.Guid _productId;
        private int _order;
        private System.Guid _linkedProductId;
        private BaseProduct _product;
        private BaseProduct _linkedProduct;
        public virtual System.Guid ProductLinkId
        {
            get
            {
                return this._productLinkId;
            }
            set
            {
                this._productLinkId = value;
            }
        }
        public virtual System.Guid ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }
        public virtual int Order
        {
            get
            {
                return this._order;
            }
            set
            {
                this._order = value;
            }
        }
        public virtual System.Guid LinkedProductId
        {
            get
            {
                return this._linkedProductId;
            }
            set
            {
                this._linkedProductId = value;
            }
        }
        public virtual BaseProduct Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }
        }
        public virtual BaseProduct LinkedProduct
        {
            get
            {
                return this._linkedProduct;
            }
            set
            {
                this._linkedProduct = value;
            }
        }
    }
    public class CrossSellingProductLink : ProductLink
    {
    }
    public class UpSellingProductLink : ProductLink
    {
    }
    public class Price
    {
        private System.Guid _priceId;
        private System.Guid _productId;
        private int _currencyId;
        private int _quantity;
        private decimal _salePrice;
        private decimal _discount;
        private decimal _discountIncludingTaxes;
        private decimal _taxes;
        private decimal _taxesConsideringDiscount;
        private decimal _salePriceInludingDiscount;
        private decimal _salePriceIncludingTaxes;
        private decimal _salePriceIncludingDiscountAndTaxes;
        private System.Nullable<decimal> _cutPrice;
        private System.Nullable<decimal> _cutPriceIncludingTaxes;
        private ReferenceProduct _product;
        private System.Collections.Generic.IEnumerable<TaxDetail> _taxDetails;
        private System.Collections.Generic.IEnumerable<DiscountDetail> _discountDetails;
        public virtual System.Guid PriceId
        {
            get
            {
                return this._priceId;
            }
            set
            {
                this._priceId = value;
            }
        }
        public virtual System.Guid ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }
        public virtual int CurrencyId
        {
            get
            {
                return this._currencyId;
            }
            set
            {
                this._currencyId = value;
            }
        }
        public virtual int Quantity
        {
            get
            {
                return this._quantity;
            }
            set
            {
                this._quantity = value;
            }
        }
        public virtual decimal SalePrice
        {
            get
            {
                return this._salePrice;
            }
            set
            {
                this._salePrice = value;
            }
        }
        public virtual decimal Discount
        {
            get
            {
                return this._discount;
            }
            set
            {
                this._discount = value;
            }
        }
        public virtual decimal DiscountIncludingTaxes
        {
            get
            {
                return this._discountIncludingTaxes;
            }
            set
            {
                this._discountIncludingTaxes = value;
            }
        }
        public virtual decimal Taxes
        {
            get
            {
                return this._taxes;
            }
            set
            {
                this._taxes = value;
            }
        }
        public virtual decimal TaxesConsideringDiscount
        {
            get
            {
                return this._taxesConsideringDiscount;
            }
            set
            {
                this._taxesConsideringDiscount = value;
            }
        }
        public virtual decimal SalePriceInludingDiscount
        {
            get
            {
                return this._salePriceInludingDiscount;
            }
            set
            {
                this._salePriceInludingDiscount = value;
            }
        }
        public virtual decimal SalePriceIncludingTaxes
        {
            get
            {
                return this._salePriceIncludingTaxes;
            }
            set
            {
                this._salePriceIncludingTaxes = value;
            }
        }
        public virtual decimal SalePriceIncludingDiscountAndTaxes
        {
            get
            {
                return this._salePriceIncludingDiscountAndTaxes;
            }
            set
            {
                this._salePriceIncludingDiscountAndTaxes = value;
            }
        }
        public virtual System.Nullable<decimal> CutPrice
        {
            get
            {
                return this._cutPrice;
            }
            set
            {
                this._cutPrice = value;
            }
        }
        public virtual System.Nullable<decimal> CutPriceIncludingTaxes
        {
            get
            {
                return this._cutPriceIncludingTaxes;
            }
            set
            {
                this._cutPriceIncludingTaxes = value;
            }
        }
        public virtual ReferenceProduct Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<TaxDetail> TaxDetails
        {
            get
            {
                return this._taxDetails;
            }
            set
            {
                this._taxDetails = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<DiscountDetail> DiscountDetails
        {
            get
            {
                return this._discountDetails;
            }
            set
            {
                this._discountDetails = value;
            }
        }
    }
    public class TaxDetail
    {
        private System.Guid _taxDetailId;
        private System.Guid _priceId;
        private string _code;
        private string _name;
        private decimal _value;
        private Price _price;
        public virtual System.Guid TaxDetailId
        {
            get
            {
                return this._taxDetailId;
            }
            set
            {
                this._taxDetailId = value;
            }
        }
        public virtual System.Guid PriceId
        {
            get
            {
                return this._priceId;
            }
            set
            {
                this._priceId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual decimal Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        public virtual Price Price
        {
            get
            {
                return this._price;
            }
            set
            {
                this._price = value;
            }
        }
    }
    public class DiscountDetail
    {
        private System.Guid _discountDetailId;
        private System.Guid _discountId;
        private System.Guid _priceId;
        private decimal _value;
        private decimal _valueIncludingTaxes;
        private Price _price;
        private Discount _discount;
        public virtual System.Guid DiscountDetailId
        {
            get
            {
                return this._discountDetailId;
            }
            set
            {
                this._discountDetailId = value;
            }
        }
        public virtual System.Guid DiscountId
        {
            get
            {
                return this._discountId;
            }
            set
            {
                this._discountId = value;
            }
        }
        public virtual System.Guid PriceId
        {
            get
            {
                return this._priceId;
            }
            set
            {
                this._priceId = value;
            }
        }
        public virtual decimal Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        public virtual decimal ValueIncludingTaxes
        {
            get
            {
                return this._valueIncludingTaxes;
            }
            set
            {
                this._valueIncludingTaxes = value;
            }
        }
        public virtual Price Price
        {
            get
            {
                return this._price;
            }
            set
            {
                this._price = value;
            }
        }
        public virtual Discount Discount
        {
            get
            {
                return this._discount;
            }
            set
            {
                this._discount = value;
            }
        }
    }
    public class Discount
    {
        private System.Guid _discountId;
        private string _code;
        private string _externalCode;
        private string _name;
        private string _description;
        private bool _isActive;
        private System.Nullable<System.DateTimeOffset> _startDate;
        private System.Nullable<System.DateTimeOffset> _endDate;
        public virtual System.Guid DiscountId
        {
            get
            {
                return this._discountId;
            }
            set
            {
                this._discountId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string ExternalCode
        {
            get
            {
                return this._externalCode;
            }
            set
            {
                this._externalCode = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        public virtual bool IsActive
        {
            get
            {
                return this._isActive;
            }
            set
            {
                this._isActive = value;
            }
        }
        public virtual System.Nullable<System.DateTimeOffset> StartDate
        {
            get
            {
                return this._startDate;
            }
            set
            {
                this._startDate = value;
            }
        }
        public virtual System.Nullable<System.DateTimeOffset> EndDate
        {
            get
            {
                return this._endDate;
            }
            set
            {
                this._endDate = value;
            }
        }
    }
    public class ExtendedDiscount : Discount
    {
    }
    public class BundleItem
    {
        private System.Guid _bundleProductId;
        private System.Guid _bundledProductId;
        private int _quantity;
        private int _order;
        private BundleProduct _bundleProduct;
        private ReferenceProduct _bundledProduct;
        public virtual System.Guid BundleProductId
        {
            get
            {
                return this._bundleProductId;
            }
            set
            {
                this._bundleProductId = value;
            }
        }
        public virtual System.Guid BundledProductId
        {
            get
            {
                return this._bundledProductId;
            }
            set
            {
                this._bundledProductId = value;
            }
        }
        public virtual int Quantity
        {
            get
            {
                return this._quantity;
            }
            set
            {
                this._quantity = value;
            }
        }
        public virtual int Order
        {
            get
            {
                return this._order;
            }
            set
            {
                this._order = value;
            }
        }
        public virtual BundleProduct BundleProduct
        {
            get
            {
                return this._bundleProduct;
            }
            set
            {
                this._bundleProduct = value;
            }
        }
        public virtual ReferenceProduct BundledProduct
        {
            get
            {
                return this._bundledProduct;
            }
            set
            {
                this._bundledProduct = value;
            }
        }
    }
    public class Carrier
    {
        private System.Guid _carrierId;
        private System.Nullable<System.Guid> _fileId;
        private string _code;
        private string _name;
        private File _file;
        public virtual System.Guid CarrierId
        {
            get
            {
                return this._carrierId;
            }
            set
            {
                this._carrierId = value;
            }
        }
        public virtual System.Nullable<System.Guid> FileId
        {
            get
            {
                return this._fileId;
            }
            set
            {
                this._fileId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual File File
        {
            get
            {
                return this._file;
            }
            set
            {
                this._file = value;
            }
        }
    }
    public class ExtendedCarrier : Carrier
    {
    }
    public class Continent
    {
        private byte _continentId;
        private string _code;
        private string _name;
        private System.Collections.Generic.IEnumerable<Country> _countries;
        public virtual byte ContinentId
        {
            get
            {
                return this._continentId;
            }
            set
            {
                this._continentId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<Country> Countries
        {
            get
            {
                return this._countries;
            }
            set
            {
                this._countries = value;
            }
        }
    }
    public class ExtendedContinent : Continent
    {
    }
    public class Country
    {
        private int _countryId;
        private byte _continentId;
        private System.Nullable<int> _currencyId;
        private string _code;
        private string _name;
        private string _iSO2Code;
        private string _iSO3Code;
        private Continent _continent;
        private Currency _currency;
        private System.Collections.Generic.IEnumerable<Region> _regions;
        public virtual int CountryId
        {
            get
            {
                return this._countryId;
            }
            set
            {
                this._countryId = value;
            }
        }
        public virtual byte ContinentId
        {
            get
            {
                return this._continentId;
            }
            set
            {
                this._continentId = value;
            }
        }
        public virtual System.Nullable<int> CurrencyId
        {
            get
            {
                return this._currencyId;
            }
            set
            {
                this._currencyId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual string ISO2Code
        {
            get
            {
                return this._iSO2Code;
            }
            set
            {
                this._iSO2Code = value;
            }
        }
        public virtual string ISO3Code
        {
            get
            {
                return this._iSO3Code;
            }
            set
            {
                this._iSO3Code = value;
            }
        }
        public virtual Continent Continent
        {
            get
            {
                return this._continent;
            }
            set
            {
                this._continent = value;
            }
        }
        public virtual Currency Currency
        {
            get
            {
                return this._currency;
            }
            set
            {
                this._currency = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<Region> Regions
        {
            get
            {
                return this._regions;
            }
            set
            {
                this._regions = value;
            }
        }
    }
    public class ExtendedCountry : Country
    {
    }
    public class Currency
    {
        private int _currencyId;
        private string _code;
        private string _name;
        private string _symbol;
        private short _precision;
        private System.Collections.Generic.IEnumerable<Country> _countries;
        public virtual int CurrencyId
        {
            get
            {
                return this._currencyId;
            }
            set
            {
                this._currencyId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual string Symbol
        {
            get
            {
                return this._symbol;
            }
            set
            {
                this._symbol = value;
            }
        }
        public virtual short Precision
        {
            get
            {
                return this._precision;
            }
            set
            {
                this._precision = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<Country> Countries
        {
            get
            {
                return this._countries;
            }
            set
            {
                this._countries = value;
            }
        }
    }
    public class ExtendedCurrency : Currency
    {
    }
    public class Region
    {
        private System.Guid _regionId;
        private int _countryId;
        private string _code;
        private string _name;
        private Country _country;
        public virtual System.Guid RegionId
        {
            get
            {
                return this._regionId;
            }
            set
            {
                this._regionId = value;
            }
        }
        public virtual int CountryId
        {
            get
            {
                return this._countryId;
            }
            set
            {
                this._countryId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual Country Country
        {
            get
            {
                return this._country;
            }
            set
            {
                this._country = value;
            }
        }
    }
    public class ExtendedRegion : Region
    {
    }
    public class OrderChannel
    {
        private System.Guid _orderChannelId;
        private string _code;
        private string _name;
        private string _description;
        public virtual System.Guid OrderChannelId
        {
            get
            {
                return this._orderChannelId;
            }
            set
            {
                this._orderChannelId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
    }
    public class ExtendedOrderChannel : OrderChannel
    {
    }
    public class Segment
    {
        private System.Guid _segmentId;
        private string _code;
        private string _name;
        public virtual System.Guid SegmentId
        {
            get
            {
                return this._segmentId;
            }
            set
            {
                this._segmentId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
    }
    public class ExtendedSegment : Segment
    {
    }
    public class Warehouse
    {
        private System.Guid _warehouseId;
        private string _code;
        private string _name;
        public virtual System.Guid WarehouseId
        {
            get
            {
                return this._warehouseId;
            }
            set
            {
                this._warehouseId = value;
            }
        }
        public virtual string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
    }
    public class ExtendedWarehouse : Warehouse
    {
    }
}
